name: Create release

on:
    workflow_dispatch:
        inputs:
            version:
                description: 'Version'
                required: true
                default: ''

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout source
              uses: actions/checkout@v2

            - name: Setup node
              uses: actions/setup-node@v3
              with:
                  node-version: '16'
                  cache: 'npm'

            - name: Install NPM dependencies
              run: npm ci

            - name: Get changelog entries
              id: changelog
              run: |
                  changelog=$("awk 'BEGIN{IGNORECASE=1;c=0;f=0;v=0}/^== Changelog ==/{c=1;next}c&&/^== /&&!/^== Changelog ==/{exit}c{if(/^= .* \([0-9]{4}-[0-9]{2}-[0-9]{2}\) =$/){v++;if(v==1){f=1;print;next}else{exit}}if(f)print}' readme.txt")
                  echo $changelog
                  echo "changes=$changelog" >> $GITHUB_OUTPUT

            - name: Build dependencies
              run: npm run build

            - name: Build plugin zip
              run: npm run plugin-zip

            - name: Tag the release
              run: |
                  git config --global user.name "GitHub Actions"
                  git config --global user.email "github-actions@github.com"
                  git tag "${{ inputs.version }}"
                  git push --tags

            - name: Create GitHub release
              id: create_github_release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ inputs.version }}
                  release_name: Release ${{ inputs.version }}
                  draft: false
                  body: ${{ steps.changelog.outputs.changes }}
                  prerelease: false

            - name: Attach plugin zip to release
              id: upload-release-asset
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ steps.create_github_release.outputs.upload_url }}
                  asset_path: ./imageshop-dam-connector.zip
                  asset_name: imageshop-dam-connector.zip
                  asset_content_type: application/zip
